security:
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"

  providers:
    app_user_provider:
      entity:
        class: App\Entity\BillingUser
        property: email

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    swagger_ui:
      pattern: ^/api/v1/doc
      stateless: true
      security: false

    login:
      pattern: ^/api/v1/auth
      stateless: true
      json_login:
        check_path: /api/v1/auth
        username_path: email
        password_path: password
        success_handler: lexik_jwt_authentication.handler.authentication_success
        failure_handler: lexik_jwt_authentication.handler.authentication_failure

    register:
      pattern: ^/api/v1/register
      stateless: true
      security: false

    api_token_refresh:
      pattern: ^/api/v1/token/refresh
      stateless: true
      refresh_jwt:
        check_path: /api/v1/token/refresh

    courses:
      pattern: ^/api/v1/courses$
      stateless: true
      security: false

    name_course:
      pattern: ^/api/v1/courses/[^/]+$
      stateless: true
      security: false

    main:
      lazy: true
      provider: app_user_provider
      stateless: true
      jwt: ~

  access_control:
    - { path: ^/api/v1/auth, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/api/v1/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/api/v1/courses/[^/]+/pay$, roles: IS_AUTHENTICATED_FULLY }
    - { path: ^/api/v1/courses$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/api/v1/courses/[^/]+$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/api/v1/doc, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/api/v1/courses/new$, roles: ROLE_SUPER_ADMIN }
    - { path: ^/api/v1/courses/[^/]+/edit$, roles: ROLE_SUPER_ADMIN }
    - { path: ^/api/v1/courses/[^/]+/delete$, roles: ROLE_SUPER_ADMIN }
    - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }


when@test:
  security:
    password_hashers:
      Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
        algorithm: auto
        cost: 4
        time_cost: 3
        memory_cost: 10
